version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672" 
    networks:
      - internal_net
  gateway:
    build: ./app/gateway
    container_name: gateway
    depends_on:
      - rabbitmq
    ports:
      - "6000:6000"
    networks:
      - internal_net

  identity:
    build: ./app/identity
    container_name: identity
    depends_on:
      - rabbitmq
    networks:
      - internal_net
  notification:
    build: ./app/notification
    container_name: notification
    depends_on:
      - rabbitmq
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes: 
   mongodb-identity-data:
